version: '3.6'

services:

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    build: ./config/Dockerfile
    restart: always
    ports:
      - 8090:80
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: "mysql"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8095:80
    env_file:
      - .env
    environment:
      PMA_HOST: "mysql"
    depends_on:
      - mysql
    

volumes:
  database: